### ISSUE TITLE
Is it possible to specify more than 1 folder to compile from?

### ISSUE THREAD

**Issue by illustratedan** [mihai-vlc/uglifyjs-folder#37]
Hi - apologies if I've missed it in the docs but was wondering if you can specify more than 1 folder to compile from? For example:
`uglifyjs-folder "folder-1, folder-2" --config-file "uglify.config.json" --o "assets/js/compiled-example.min.js"`

**Comment by mihai-vlc** [comment]
The end result would be the js files from the 2 folders concatenated.

You can do this by running the command twice and then concatenating the result.

Something similar to:
```
uglifyjs-folder "folder-1" --config-file "uglify.config.json" -o "tmp/folder1.min.js"
uglifyjs-folder "folder-2" --config-file "uglify.config.json" -o "tmp/folder2.min.js"
cat tmp/folder1.min.js tmp/folder2.min.js > assets/js/compiled-example.min.js
```

Please close the issue if this solution works for you.

**Comment by illustratedan** [comment]
Apologies for the late reply, thanks for this 👍
