### ISSUE TITLE
window.onload does not work when minified

### ISSUE THREAD

**Issue by MDGDesign** [mihai-vlc/uglifyjs-folder#38]
Hey all,

I have several files in a folder for specific needs. Some use pure vanilla JS and other some jQuery.
When not miniifying, the different scripts that uses `window.onload` does work as expected with no errors.

But when I do minified my scripts, the different `window.onload` from different files, do not work except for the very last one. No errors in the console.

If I write the following in different files and minify it :
```js
window.onload = function() { 
 // My code 
 console.log( "HELLO TO YOU" );
};
// Other window.onload form other files ....
```
It does not execute in the browser except for the last one only.

But I f I write the following in the same file many times or from different files (which is considered the same as above):
```js
jQuery(document).ready(function() {
   // My same code
 console.log( "HELLO TO YOU" );
});
 // Other jQuery(document).ready(function() form other files ....
```
It works fine!

The output of these are:
```js

// other code before...
// functions ....
// jQuery ....
)),
window.onload = function() {
  console.log("Hello to someone")
   // Does not get executed
}
,
window.onload = function() {
    console.log("Hello to me")
 // Does not get executed
}
,
window.onload = function() {
    console.log("Hello to me")
 // Does not get executed
}
,
window.onload = function() {
     console.log("Hello to me")
 // Does  get executed
}
;
```

Any ideas??

Probably the best practice, should be only to have one single call of the 'window.onload', but if you want to seperate your scripts for specific needs, then this does not work.

**Comment by mihai-vlc** [comment]
If you need to register multiple `load` event listeners on a single page you should use `window.addEventListener('load'`.

If they work when they are not minified you probably have the scripts loaded on separate pages.
For that you may want to experiment with generating 2 bundles:
- shared.min.js - which contains the libraries and code that is shared between all the pages
- page1.min.js - code that is specific for that page
- page2.min.js 
- ...

You can create separate folders for each bundle.

**Comment by marcdegagne** [comment]
Thanks @mihai-vlc !

I ended up cleaning my code to make it work and use `window.addEventListener('load)`.
Parctical app thanks for your work.
